### ISSUE TITLE
List beers as "The Regulars" -> combine batches into single 'beers'

### ISSUE THREAD

**Issue by mikeyweigand** [ckdake/stalchemist.beer#1]
List beers as:
- the 'regulars' - eg. rye saison, red clay ipa
  - lists all batches/variations
- full/archive list of all batches
  - sortable/searchable table of batch number, name, style, brew date

Link beers:
- individual batches of same/similar base recipe are linked - eg. rye shower (30) and clementine's crye baby saison (31) linked to 'regular' rye saison.

**Comment by ckdake** [comment]
This is pretty much in! Needs more data entry though.
